### ISSUE TITLE
ImmuneML requires scikit-learn==1.2.2 to work, the default pip install uses scikit-learn==1.3.0

### ISSUE THREAD

**Issue by CokieLee** [uio-bmi/immuneML#158]
Hello,
I noticed that the default process of installing immuneml using pip didn't work at first because the statement "from sklearn.metrics import SCORERS" (in the file /immuneML/ml_methods/SklearnMethod.py) causes a runtime error (shows in the attached photo).
![8_1_23_ImmuneMLError](https://github.com/uio-bmi/immuneML/assets/52169237/9537eb23-d6ec-4367-9c4b-08feead5c8dd)

It appears that statement is no longer a supported syntax by scikit-learn. After changing my scikit-learn version from default (most up to date) version 1.3.0, to version 1.2.2, ImmuneML appeared to work as intended.

I was using python version 3.9.6 with a virtual environment, on a linux machine (Red hat enterprise server), and pip version 23.2.1. I believe all the other packages installed were the most recent available versions.

Just wanted to let you guys know, as it had me confused for a minute,
Thanks!

**Comment by pavlovicmilena** [comment]
Thanks for letting us know! We hope to fix this soon :)

**Comment by pavlovicmilena** [comment]
This is fixed in version 2.2.6. Sorry for the slow response!
