### ISSUE TITLE
IMGT positions are computed wrong

### ISSUE THREAD

**Issue by LonnekeScheffer** [uio-bmi/immuneML#159]
correct is shown here: https://www.imgt.org/IMGTScientificChart/Numbering/IMGTIGVLsuperfamily.html

we add 0.001 for each position (we get e.g. [112.005, 112.01, 112.15] when it should be [112.1, 112.10, 112.15...])
should be a small fix, but need to take a thorough look to see if any other parts of the code depends on the way we do it currently

**Comment by pavlovicmilena** [comment]
Fixed in PR#163
