### ISSUE TITLE
Galaxy interface trims CDR3 residues in create dataset

### ISSUE THREAD

**Issue by agirgis3** [uio-bmi/immuneML#167]
Hello,  in attempting to generate immuneML datasets using the galaxy interface, I am unable to specify trim_leading_trailing: false in the 'simple' parameter mode. I would like more control by using my own .yaml file in the galaxy Create Dataset interface. 

 However, I am also unable to upload my own .yaml specification for this purpose, because it seems the data files are loaded using some temporary cache that I do not know the filepath for. 

Please let me know if this query makes sense, if not happy to elaborate.

**Comment by LonnekeScheffer** [comment]
Hi Alexander, thanks for reaching out! What type of dataset are you working with? Sequence/receptor or repertoire dataset?

**Comment by agirgis3** [comment]
Hi Lonneke, I am working with sequence datasets of unpaired TRB chains, provided in AIRR format.
