### ISSUE TITLE
KeyError in exploratory analysis

### ISSUE THREAD

**Issue by KanduriC** [uio-bmi/immuneML#29]
I am trying to run this yaml instruction ([repertoire_implanting_rate__0.001_-_ml_instruction_yaml.txt](https://github.com/uio-bmi/immuneML/files/5488442/repertoire_implanting_rate__0.001_-_ml_instruction_yaml.txt)) using this [dataset](https://drive.google.com/drive/folders/1FPauiKw6kBHqRvyG69u4tznoWF5TXjs5?usp=sharing) and a file required by a specific report ([motif_file_2.txt](https://github.com/uio-bmi/immuneML/files/5488438/motif_file_2.txt)). I encounter the following error ([stderr.txt](https://github.com/uio-bmi/immuneML/files/5488436/stderr.txt)). Attached is immuneML's log file ([log.txt](https://github.com/uio-bmi/immuneML/files/5488456/log.txt)). Could you help me figure out what is going wrong here. Thanks!

**Comment by pavlovicmilena** [comment]
Hi Chakri, I updated the code, it should work now 🤓
