### ISSUE TITLE
error when exporting evenness encoded data as design matrix

### ISSUE THREAD

**Issue by KanduriC** [uio-bmi/immuneML#90]
Hi!

I am  trying to export evenness encoding as design matrix using the following yaml specification: 

![Screenshot 2021-03-30 at 11 19 13](https://user-images.githubusercontent.com/8395053/112965735-d2c99b00-9149-11eb-8529-5128faa05811.png)

I get the following error:

![Screenshot 2021-03-30 at 11 20 16](https://user-images.githubusercontent.com/8395053/112965853-f1c82d00-9149-11eb-9bd2-6d841cd68164.png)

Could you help me figure out what is wrong here ..Are evenness encoding and design matrix exporter not compatible !? I am using version 1.02. Thanks!

**Comment by pavlovicmilena** [comment]
It should all work now :) 🙏
